dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: mulder
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: scully
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
